### ISSUE TITLE
Reduce bottom padding of headers

### ISSUE THREAD

**Issue by stevenbister** [Blink-SEO/Blink#70]
could you change
```css
.pb-24 {
    padding-bottom: 6rem;
}
```
to
```css
.pb-12 {
    padding-bottom: 3rem;
}
```
